module.exports = {
	namespace: "all",
	commands: 	require("./src/help")
        .concat(require("./src/dataset"))
        .concat(require("./src/context"))
        .concat(require("./src/var"))
        .concat(require("./src/json"))
        .concat(require("./src/table"))
        .concat(require("./src/stat"))
        .concat(require("./src/chart"))
        .concat(require("./src/export"))
        .concat(require("./src/version"))
        .concat(require("./src/dps"))
        .concat(require("./src/log"))
        .concat(require("./src/time-serie"))
        .concat(require("./src/javascript"))
        .concat(require("./src/html"))
        .concat(require("./src/xml"))
        .concat(require("./src/csv"))
        .concat(require("./src/text"))
}